var questions=[{"question":"....pple",
               "option1":"B",
               "option2":"A",
               "option3":"C",
               "option4":"E",
               "answer":"2"
               },{
               "question":"...all",
               "option1":"c",
               "option2":"B",
               "option3":"m",
               "option4":"S",
               "answer":"2"
               },{
               "question":"....lock",
               "option1":"C",
               "option2":"D",
               "option3":"A",
               "option4":"N",
               "answer":"1"
               },{
               "question":"D...g",
               "option1":"t",
               "option2":"a",
               "option3":"o",
               "option4":"e",
               "answer":"3"
               },{
               "question":"....gg",
               "option1":"Z",
               "option2":"R",
               "option3":"E",
               "option4":"O",
               "answer":"3"
               },{
               "question":"....ish",
               "option1":"S",
               "option2":"F",
               "option3":"Z",
               "option4":"K",
               "answer":"2"
               },{
               "question":"R....bbit",
               "option1":"b",
               "option2":"c",
               "option3":"a",
               "option4":"e",
               "answer":"3"
               },{
               "question":"....mbrella",
               "option1":"M",
               "option2":"W",
               "option3":"U",
               "option4":"A",
               "answer":"3"
               },{
               "question":"....un",
               "option1":"R",
               "option2":"F",
               "option3":"S",
               "option4":"J",
               "answer":"3"
               },{
               "question":"....onkey",
               "option1":"N",
               "option2":"M",
               "option3":"Z",
               "option4":"H",
               "answer":"2"
               }];